import type { Metadata } from "next";
import Link from "next/link";
import { localePath } from "@/lib/i18n";
import { getPracticeSets } from "@/lib/queries";
import { pageMeta } from "@/lib/seo";
import type { Locale } from "@/lib/site-config";

export function generateMetadata({ params }: { params: { locale: Locale } }): Metadata {
  const hi = params.locale === "hi";
  return pageMeta(params.locale, "/practice",
    hi ? "प्रैक्टिस टेस्ट" : "Free Practice Tests — SSC, RRB MCQs",
    hi ? "विषयवार निःशुल्क अभ्यास सेट — उत्तर व व्याख्या सहित।" : "Free subject-wise MCQ practice sets with answers and explanations for SSC and RRB exams.");
}

export default async function PracticePage({ params }: { params: { locale: Locale } }) {
  const sets = await getPracticeSets();
  const hi = params.locale === "hi";
  return (
    <div className="wrap py-8">
      <h1 className="text-2xl font-extrabold tracking-tight">🧪 {hi ? "प्रैक्टिस टेस्ट" : "Practice tests"}</h1>
      <p className="mt-1 max-w-2xl text-sm text-slate-500">
        {hi ? "AI-निर्मित अभ्यास प्रश्न — महत्वपूर्ण तथ्यों की पुष्टि स्वयं करें।" : "Generated by AI — verify important facts before relying on them."}
      </p>
      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {sets.map((set) => (
          <Link key={set.id} href={localePath(params.locale, `/practice/${set.id}`)} className="card p-5 hover:border-brand-200 hover:shadow-lift">
            <p className="pill mb-2 bg-accent-50 text-accent-700">{set.subject}</p>
            <h2 className="text-[15px] font-extrabold leading-snug">{set.title}</h2>
            <p className="mt-2 text-xs text-slate-500">{set.draw ?? set.questions.length} {hi ? "प्रश्न" : "questions"} · {hi ? "उत्तर व व्याख्या सहित" : "with answers & explanations"}</p>
          </Link>
        ))}
      </div>
    </div>
  );
}
