import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import QuizPlayer from "@/components/QuizPlayer";
import { localePath } from "@/lib/i18n";
import { getPracticeSet } from "@/lib/queries";
import { pageMeta } from "@/lib/seo";
import type { Locale } from "@/lib/site-config";

export async function generateMetadata({ params }: { params: { locale: Locale; id: string } }): Promise<Metadata> {
  const set = await getPracticeSet(parseInt(params.id, 10));
  return pageMeta(params.locale, `/practice/${params.id}`,
    set ? `${set.title} — Free MCQs` : "Practice Set",
    set ? `${set.draw ?? set.questions.length} ${set.subject} practice questions with answers and explanations.` : "Practice set");
}

export default async function PracticeSetPage({ params }: { params: { locale: Locale; id: string } }) {
  const set = await getPracticeSet(parseInt(params.id, 10));
  if (!set) notFound();
  const hi = params.locale === "hi";
  return (
    <div className="wrap max-w-3xl py-8">
      <Link href={localePath(params.locale, "/practice")} className="text-sm font-bold text-brand-700">← {hi ? "सभी प्रैक्टिस टेस्ट" : "All practice tests"}</Link>
      <h1 className="mt-2 text-2xl font-extrabold tracking-tight">{set.title}</h1>
      <p className="mb-5 mt-1 text-sm text-slate-500">{set.draw ?? set.questions.length} {hi ? "प्रश्न" : "questions"} · {set.subject}</p>
      <QuizPlayer set={set} locale={params.locale} />
      <p className="mt-4 text-center text-xs text-slate-400">
        {hi ? "AI द्वारा निर्मित — महत्वपूर्ण तथ्यों की पुष्टि करें।" : "Generated by AI — verify important facts before relying on them."}
      </p>
    </div>
  );
}
